export enum FIELD_TYPE {
  AMOUNT = 'AMOUNT',
  CHECKBOX = 'CHECKBOX',
  DATE = 'DATE',
  FREE_TEXT = 'FREE_TEXT',
  PERCENTAGE = 'PERCENTAGE',
  RADIOBUTTON = 'RADIOBUTTON',
  RADIOBUTTON_WITH_ICON = 'RADIOBUTTON_WITH_ICON',
  SELECT = 'SELECT',
  TEXT = 'TEXT'
}
